Add `cacheTo` argument to `ci` action
devcontainers/ci pull request #300
Opened 2024-09-02 15:29 UTC by sebst

Added the argument `cacheTo` to the action (#299) so that a cache image can be written to a registry.

2024-09-02 15:30 UTC, sebst commented
@microsoft-github-policy-service agree

2024-09-03 09:04 UTC, chrmarti requested changes
Thanks for the PR! Left a few comments.

2024-09-03 09:04 UTC, chrmarti commented on azdo-task/DevcontainersCi/task.json
> +      "name": "cacheTo",
Also document in docs/azure-devops-task.md.

2024-09-03 09:04 UTC, chrmarti commented on action.yml
> +  cacheTo:
Also document in docs/github-action.md

2024-09-03 09:04 UTC, chrmarti commented on github-action/src/main.ts
> +		const cacheTo = emptyStringAsUndefined(core.getInput('cacheTo'));
Support array?

2024-09-06 07:24 UTC, sebst commented
Any update?

2024-09-18 14:16 UTC, sebst commented
Any update?

2024-10-08 22:09 UTC, samruddhikhandale requested changes
Thanks, overall it looks good.

Left one comment

2024-10-08 22:09 UTC, samruddhikhandale commented on github-action/src/main.ts
> +		const cacheTo: string[] = core.getMultilineInput('cacheFrom');
```suggestion
		const cacheTo: string[] = core.getMultilineInput('cacheTo');
```

2024-10-08 22:19 UTC, sebst commented
> Thanks, overall it looks good.
> 
> Left one comment

Thanks! Fixed the typo

2024-10-08 22:21 UTC, samruddhikhandale approved these changes

2024-10-08 23:50 UTC, samruddhikhandale commented
> Ensure you have run scripts/build-local.sh

@sebst Can you help fix the failing action, see [here](https://github.com/devcontainers/ci/actions/runs/11244625749/job/31263435255?pr=300#step:10:2223)

2024-10-09 08:33 UTC, sebst commented
> > Ensure you have run scripts/build-local.sh
> 
> @sebst Can you help fix the failing action, see [here](https://github.com/devcontainers/ci/actions/runs/11244625749/job/31263435255?pr=300#step:10:2223)

Done

2024-10-10 16:41 UTC, sebst commented
@samruddhikhandale could you please restart the pipeline to see if the last commit fixes the issue?

2024-10-14 11:33 UTC, sebst commented
Can this be merged now?

@samruddhikhandale @chrmarti @stuartleeks @bamurtaugh

2024-10-14 17:42 UTC, samruddhikhandale approved these changes

2024-10-14 18:13 UTC, samruddhikhandale commented
Hi @sebst, thanks for your patience. 
We are waiting for another review from @chrmarti, we'd merge shortly. Thanks!

2024-10-22 12:08 UTC, sebst commented
Just a friendly reminder. 

@samruddhikhandale @chrmarti @stuartleeks @bamurtaugh

2024-11-04 16:37 UTC, sebst commented
Just another friendly reminder.

@samruddhikhandale @chrmarti @stuartleeks @bamurtaugh

2024-11-09 13:00 UTC, sebst commented
> Hi @sebst, thanks for your patience. 
> 
> We are waiting for another review from @chrmarti, we'd merge shortly. Thanks! 

Is there any chance we get that merged?

@chrmarti

2024-12-12 14:09 UTC, sebst commented
@samruddhikhandale @chrmarti @stuartleeks @bamurtaugh

This PR is open for more than 3 months now but it's just a small change.

Is there anything I could do on my end to get this merged?

Appreciate any feedback!

2024-12-19 09:48 UTC, chrmarti approved these changes
LGTM, thanks!

2024-12-19 09:48 UTC, merged